### ISSUE TITLE
No route was found matching the URL and request method

### ISSUE THREAD

**Issue by handeweg** [onlyutkarsh/VSOStatusInspector#10]
The Monitoring does not seem to work anymore after the move to Azure DevOps

**Comment by onlyutkarsh** [comment]
Hello @handeweg, thanks for raising this - unfortunately, the endpoint I was using has become obsolete. I am talking with the product team to see if there will be new endpoint available. I will be able to fix the issue then.

**Comment by handeweg** [comment]
Hi Utkarsh

I found the following url :
https://azure.microsoft.com/en-us/support/devops/

Hope this helps

best regards
Hans

Op wo 7 nov. 2018 om 09:37 schreef Utkarsh Shigihalli <
notifications@github.com>:

**Comment by onlyutkarsh** [comment]
Hey @handeweg This is fixed in the [latest version](https://marketplace.visualstudio.com/items?itemName=UtkarshShigihalliandTarunArora.VSTSStatusInspector).
