### ISSUE TITLE
Status displayed as unknown due to changes in Html structure of status web page

### ISSUE THREAD

**Issue by stebueh** [onlyutkarsh/VSOStatusInspector#3]
The Html structure of the VSO status web page at https://www.visualstudio.com/en-us/support/support-overview-vs.aspx has changed, therefore the extension shows 'unknown' as status of VSO.

**Comment by stebueh** [comment]
PR #4 fixes the xpath expression to match the elements in the current Html structure of the VSO status web page

**Comment by onlyutkarsh** [comment]
Hey @stebueh thanks for the fix. Appreciate it. Can you please download and test [latest version](http://vsixgallery.com/extensions/beb913a8-333c-41b1-a736-878cebad3bc6/VSTS%20Status%20Inspector%20v1.0.45.vsix) and let me know if it works fine? P.S I also changed the name to VSTS Status inspector for better searchability. Once you confirm, I will upload it to VS gallery.

**Comment by stebueh** [comment]
Hey @onlyutkarsh thank you for your work. I had to uninstall the currently installed version to be able to install the latest version - it might be that the version information in the manifest file needs to be updated to allow existing users to install the updated version.

Apart from that, the extension now shows the VSTS status correctly.

**Comment by onlyutkarsh** [comment]
@stebueh Great! I will do that before I publish to the VS gallery.

**Comment by onlyutkarsh** [comment]
@stebueh Great! Thanks for your contribution. Updated the version number and the new version is now in the [Visual Studio gallery](https://visualstudiogallery.msdn.microsoft.com/e87c82b9-dced-4fe2-9a40-f90139c56882)!

**Comment by onlyutkarsh** [comment]
Fixed in #4
