### ISSUE TITLE
No extension update notification

### ISSUE THREAD

**Issue by vercellone** [onlyutkarsh/VSOStatusInspector#9]
Your appveyor.yml publishes to a different gallery than previous versions.  VSIX Gallery vs. Visual Studio Gallery.  Users like myself currently have 2 options to upgrade:
1. [Subscribe to the VSIX Gallery feed](http://vsixgallery.com/guide/feed/).
1. Download and install the artifact directly from appveyor.

I believe you can use tfx-cli to publish to the Visual Studio Marketplace (F.K.A. Gallery).  Feel free to look over my vsts-btdf-tasks [appveyor.yml](https://github.com/vercellone/vsts-btdf-tasks/blob/master/appveyor.yml) for hints.

See also: [Package and Publish an integration to the Marketplace
](https://www.visualstudio.com/en-us/docs/integrate/extensions/publish/integration)

**Comment by onlyutkarsh** [comment]
You cannot use tfx-cli to publish Visual Studio extensions. You can only publish VSTS/TFS extension to the marketplace using tfx-cli.

I use VSIXGallery.com for dev builds. Since the VSIX published there are from CI build, there is a chance of features not working. Hence, only when the I tested it on a couple of machines, I end up publishing in the marketplace.

**Comment by vercellone** [comment]
Reasonable enough.  When do expect you'll publish the latest to the Visual Studio Gallery?

**Comment by onlyutkarsh** [comment]
It's already in the Visual Studio Gallery - all Visual Studio extensions appear in the VSmarketplace after some time. So latest version is [here](https://marketplace.visualstudio.com/items?itemName=UtkarshShigihalliandTarunArora.VSTSStatusInspector). You should also see the notification about the update in the Visual Studio.

**Comment by onlyutkarsh** [comment]
@vercellone I have published a new version of this extension. If you are still interested, please try it out from [here](https://marketplace.visualstudio.com/items?itemName=UtkarshShigihalliandTarunArora.VSTSStatusInspector)
